### ISSUE TITLE
Test Generation not possible with RESOURCE_TEST_GENERATION only

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#141]
My user has this permission: 

Permission | Global | Action | Environment | Res. Group | Res. Type | Res. Type Cat.
-- | -- | -- | -- | -- | -- | --
RESOURCE_TEST_GENERATION |   | READ |   |   |   | ANY

Calling Test Generation gives this error:
```
A general System Failure occurred! 
/pages/generationTest.xhtml @17,79 listener="#{generationTestController.init}": javax.ejb.EJBTransactionRolledbackException: Not Authorized! You're not allowed to You do not have the permission to view the results of test generation!
```

I should still be able to successfully call Test Generation but not be able to view the rendered template.

**Comment by RetGal** [comment]
Fixed in pr #148

**Comment by yvespp** [comment]
Now with RESOURCE_TEST_GENERATION ALL ANY I can call test generation which is good but I can also see the rendered templates, this should only possible with role RESOURCE_TEST_GENERATION_RESULT.

**Comment by yvespp** [comment]
I looks like this atm:
![image](https://user-images.githubusercontent.com/15231595/29062252-4462097e-7c21-11e7-9a5b-9b6290078e8f.png)

The name of the templates should be shown for all templates (`You do not have the required permission to view the generated templates` should not be shown) but the content should not be visible (can't open the template view by clicking on the name).

**Comment by RetGal** [comment]
Fixed in pr #156
![test_generation](https://user-images.githubusercontent.com/19471064/29063396-e7e70550-7c25-11e7-80ae-bbaab3171786.png)

**Comment by yvespp** [comment]
I gave RESOURCE_TEST_GENERATION_RESULT ALL ANY to the viewer role, but clicking an a template still shows me `You don't have the permission to see the content of this template.`
![image](https://user-images.githubusercontent.com/15231595/29070161-55d798c8-7c3e-11e7-803a-385f288fa6f4.png)

With the role config_admin it works but I didn't find the permission that was responsible for it working.

**Comment by RetGal** [comment]
Fixed with pr #160
