### ISSUE TITLE
Permission DEPLOYMENT READ has to many rights

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#142]
Users with permission DEPLOYMENT READ can create and confirm deployments on all envs.

This permissions should only able to see deployments but not create or confirm them. The buttons for `Add deployment` and `Redeployment` should not be shown if the user has no CREATE permission on any environment.
If a user has the permission to CREATE deployments only on some environments, he should only be able to create deployments there and only requests on environments where he has no CREATE permission

**Comment by yvespp** [comment]
DEPLOYMENT READ: can view the deployment tab, get deployments via Rest, only env=all is valid for READ.
DEPLOYMENT CREATE: can create, confirm deployments and change deployment requests on all or specific envs, limited to all or specific application servers.

**Comment by RetGal** [comment]
Fixed in pr #146

**Comment by yvespp** [comment]
With the viewer role, which only has DEPLOYMENT READ ANY, I can still see the create/redeployment button/links. They should be hidden.
![image](https://user-images.githubusercontent.com/15231595/29043741-be72cab0-7bbc-11e7-8a81-e8f17108eb6c.png)

Clicking on the buttons confirm/reject actually works as viewer.

**Comment by RetGal** [comment]
Fixed in pr #155, need to update the documentation

**Comment by yvespp** [comment]
A user should still be able to create deployment **requests** if he/she has no right to confirm deployments. The action of the DEPLOYMENT permission should be used like this:
* READ to view all deployments, view logs
* CREATE to create new deployment requests -> buttons `Add deployment`, `Redeployment` shown
* UPDATE to confirm requests, change date, cancel. Can't create requests, buttons `Add deployment`, `Redeployment` not shown.

Sorry for the back and forth...

**Comment by RetGal** [comment]
Should be fixed with pr #159 
reminder: need to update the documentation

**Comment by yvespp** [comment]
@RetGal Everything works now, thanks for the patience 👍 
I'm going to cut the release now.
